name: Cypress Tests

on:
  push:        # roda em qualquer push
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      CYPRESS_LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      CYPRESS_LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

    steps:
      - name: Baixando projeto
        uses: actions/checkout@v4

      - name: Executando teste cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/login.cy.js

      - name: Subindo relatório
        if: always() # Certifique-se de que o relatório será salvo mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report # Nome do artifact
          path: mochawesome-report # Caminho onde o relatório está salvo
          retention-days: 3 # Define que o artifact expira em 3 dias

      - name: Subindo screenshot
        if: always() # Certifique-se de que o relatório será salvo mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshot # Nome do artifact
          path: cypress/screenshots # Caminho onde o relatório está salvo
          retention-days: 3 # Define que o artifact expira em 3 dias

      - name: Subindo video
        if: always() # Certifique-se de que o relatório será salvo mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos # Nome do artifact
          path: cypress/videos # Caminho onde o relatório está salvo
          retention-days: 3 # Define que o artifact expira em 3 dias